.PHONY: postinstall

postinstall:
	mkdir -p ~/.vim/_backup
	mkdir -p ~/.vim/_temp
	curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
		https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

# TODO: run vim to install plugins and CoC extensions

